// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OpenaiRealtimeController from "./openai_realtime_controller"
application.register("openai-realtime", OpenaiRealtimeController)

import OpenaiTranscriptionController from "./openai_transcription_controller"
application.register("openai-transcription", OpenaiTranscriptionController)
