// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OpenaiRealtimeController from "./openai_realtime_controller"
application.register("openai-realtime", OpenaiRealtimeController)

import OpenaiTranscriptionController from "./openai_transcription_controller"
application.register("openai-transcription", OpenaiTranscriptionController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import GrammarErrorController from "./grammar_error_controller"
application.register("grammar-error", GrammarErrorController)

import TranscriptionController from "./transcription_controller"
application.register("transcription", TranscriptionController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import TrialCountdownController from "./trial_countdown_controller"
application.register("trial-countdown", TrialCountdownController)
